// <auto-generated />
using System;
using IBshopDemo.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IBshopDemo.Migrations
{
    [DbContext(typeof(TestHadadianContext))]
    [Migration("20240910100103_initail")]
    partial class initail
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.20")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IBshopDemo.Models.ArtMonthlyReport", b =>
                {
                    b.Property<int>("ArtMonthlyReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ArtMonthlyReportId"));

                    b.Property<int>("AppliedMotionAvgTime")
                        .HasColumnType("int");

                    b.Property<int>("ArchiveDesignQty")
                        .HasColumnType("int");

                    b.Property<int>("ArchivedmotionQty")
                        .HasColumnType("int");

                    b.Property<int>("BannerDesignQty")
                        .HasColumnType("int");

                    b.Property<int>("BrochureDesignAvgTime")
                        .HasColumnType("int");

                    b.Property<int>("BrochureDesignQty")
                        .HasColumnType("int");

                    b.Property<int>("CompStudy")
                        .HasColumnType("int");

                    b.Property<int>("GifDesignAvgTime")
                        .HasColumnType("int");

                    b.Property<int>("GifDesignQty")
                        .HasColumnType("int");

                    b.Property<int>("MediaFailureQty")
                        .HasColumnType("int");

                    b.Property<string>("Month")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MonthNumber")
                        .HasColumnType("int");

                    b.Property<int>("MotionQty")
                        .HasColumnType("int");

                    b.Property<int>("MrkReq")
                        .HasColumnType("int");

                    b.Property<int>("NarrationEditQty")
                        .HasColumnType("int");

                    b.Property<int>("RecordedQty")
                        .HasColumnType("int");

                    b.Property<int>("RecordedvideoQty")
                        .HasColumnType("int");

                    b.Property<int>("SiteBannerAvgTime")
                        .HasColumnType("int");

                    b.Property<int>("StandDesigQty")
                        .HasColumnType("int");

                    b.Property<int>("StandDesignAvgTime")
                        .HasColumnType("int");

                    b.Property<int>("StoryDesignAvgTime")
                        .HasColumnType("int");

                    b.Property<int>("StoryDesignQty")
                        .HasColumnType("int");

                    b.Property<int>("VideoArchiveQty")
                        .HasColumnType("int");

                    b.Property<int>("VideoProduceAvgTime")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("ArtMonthlyReportId");

                    b.ToTable("ArtMonthlyReports");
                });

            modelBuilder.Entity("IBshopDemo.Models.BranchKpi", b =>
                {
                    b.Property<string>("KpibranchCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BranchCap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BrcClient")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BrcCnf")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BrnReqQty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClienttoIssue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConIntMonPercentage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kllevel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MrkSpv")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewUser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PurchaseAvgTime")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WrongIssue")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WrongQty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("WrsupReq")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KpibranchCode");

                    b.ToTable("BranchKpis");
                });

            modelBuilder.Entity("IBshopDemo.Models.BranchManagerMonthlyReport", b =>
                {
                    b.Property<int>("BranchManagerMonthlyReportIdBranchManagerMonthlyReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BranchManagerMonthlyReportIdBranchManagerMonthlyReportId"));

                    b.Property<int>("AssuranceMrkmtgqty")
                        .HasColumnType("int");

                    b.Property<int>("AssuranceSuccessMtgqty")
                        .HasColumnType("int");

                    b.Property<int>("BranchCode")
                        .HasColumnType("int");

                    b.Property<string>("BranchLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ComplainantQty")
                        .HasColumnType("int");

                    b.Property<int>("Conciliation")
                        .HasColumnType("int");

                    b.Property<int>("CoursesMrkmtgfirstAgreementQty")
                        .HasColumnType("int");

                    b.Property<int>("CoursesMrkmtgqty")
                        .HasColumnType("int");

                    b.Property<int>("CoursesReq")
                        .HasColumnType("int");

                    b.Property<int>("DebtSharesMrkmtgqty")
                        .HasColumnType("int");

                    b.Property<int>("DebtSharesSuccessMtgqty")
                        .HasColumnType("int");

                    b.Property<int>("IBcardMrkmtgqty")
                        .HasColumnType("int");

                    b.Property<int>("IBcardSuccessMtgqty")
                        .HasColumnType("int");

                    b.Property<int>("IBcrowdMrkmtgqty")
                        .HasColumnType("int");

                    b.Property<int>("IBcrowdSuccessMtgqty")
                        .HasColumnType("int");

                    b.Property<int>("InvesmentSuccessMtgqty")
                        .HasColumnType("int");

                    b.Property<int>("InvestmentMrkmtgqty")
                        .HasColumnType("int");

                    b.Property<string>("Month")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MonthNumber")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("BranchManagerMonthlyReportIdBranchManagerMonthlyReportId");

                    b.ToTable("BranchManagerMonthlyReports");
                });

            modelBuilder.Entity("IBshopDemo.Models.BranchRanking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Andokhtehrank")
                        .HasColumnType("int");

                    b.Property<int?>("Bimehrank")
                        .HasColumnType("int");

                    b.Property<int?>("BranchId")
                        .HasColumnType("int");

                    b.Property<int?>("BranchRankingId")
                        .HasColumnType("int");

                    b.Property<int?>("GanjinehRank")
                        .HasColumnType("int");

                    b.Property<int?>("IBcrowdrank")
                        .HasColumnType("int");

                    b.Property<int?>("Productrank")
                        .HasColumnType("int");

                    b.Property<int?>("Sandoghrank")
                        .HasColumnType("int");

                    b.Property<int?>("SatisfactionRank")
                        .HasColumnType("int");

                    b.Property<int?>("ServatRank")
                        .HasColumnType("int");

                    b.Property<int?>("Servicerank")
                        .HasColumnType("int");

                    b.Property<int?>("TotalRank")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("BranchRankings");
                });

            modelBuilder.Entity("IBshopDemo.Models.BranchesInfo", b =>
                {
                    b.Property<int>("BranchCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BranchCode"));

                    b.Property<string>("BranchLocation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BranchManager")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BranchCode");

                    b.ToTable("BranchesInfos");
                });

            modelBuilder.Entity("IBshopDemo.Models.BranchesMonthlyReport", b =>
                {
                    b.Property<int>("BranchMonthlyReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BranchMonthlyReportId"));

                    b.Property<int>("AccBranchQty")
                        .HasColumnType("int");

                    b.Property<int>("BranchCompCheckedQty")
                        .HasColumnType("int");

                    b.Property<int>("BranchCompQty")
                        .HasColumnType("int");

                    b.Property<int>("BranchInfractionQty")
                        .HasColumnType("int");

                    b.Property<int>("BranchMonQty")
                        .HasColumnType("int");

                    b.Property<int>("BranchReformQty")
                        .HasColumnType("int");

                    b.Property<int>("BranchTickects")
                        .HasColumnType("int");

                    b.Property<int>("BranchpersonnelQty")
                        .HasColumnType("int");

                    b.Property<int>("CandstoDevelopmentQty")
                        .HasColumnType("int");

                    b.Property<int>("CoursesNeedQty")
                        .HasColumnType("int");

                    b.Property<int>("CoursesQty")
                        .HasColumnType("int");

                    b.Property<int>("CrttoCusQty")
                        .HasColumnType("int");

                    b.Property<int>("FacilityReqQty")
                        .HasColumnType("int");

                    b.Property<int>("FundSettlementQty")
                        .HasColumnType("int");

                    b.Property<int>("FundsConflictsQty")
                        .HasColumnType("int");

                    b.Property<int>("IBcrowdKpiconflictQty")
                        .HasColumnType("int");

                    b.Property<int>("IbcardConflictBranchQty")
                        .HasColumnType("int");

                    b.Property<int>("IbcrowdConflictBranchQty")
                        .HasColumnType("int");

                    b.Property<int>("InpersonBranchQty")
                        .HasColumnType("int");

                    b.Property<int>("InvestmentCapitalConflicts")
                        .HasColumnType("int");

                    b.Property<string>("Month")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MonthNumber")
                        .HasColumnType("int");

                    b.Property<int>("MrkpacTobranchQty")
                        .HasColumnType("int");

                    b.Property<int>("OnlineExamsQty")
                        .HasColumnType("int");

                    b.Property<int>("PersonnelAdReqQty")
                        .HasColumnType("int");

                    b.Property<int>("PersonnelAssuranceReqQty")
                        .HasColumnType("int");

                    b.Property<int>("ReportsConflictsToBranchQty")
                        .HasColumnType("int");

                    b.Property<int>("SendtoBranch")
                        .HasColumnType("int");

                    b.Property<int>("ServicesToBranchQty")
                        .HasColumnType("int");

                    b.Property<int>("SwsolvedQty")
                        .HasColumnType("int");

                    b.Property<int>("TicketConflictsQty")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("BranchMonthlyReportId");

                    b.ToTable("BranchesMonthlyReports");
                });

            modelBuilder.Entity("IBshopDemo.Models.CrmMonthlyReport", b =>
                {
                    b.Property<int>("Crmmrid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Crmmrid"));

                    b.Property<int>("AndookhtehIssuesQty")
                        .HasColumnType("int");

                    b.Property<double>("AndookhtehIssuesVol")
                        .HasColumnType("float");

                    b.Property<int>("AndookhtehicketQty")
                        .HasColumnType("int");

                    b.Property<double>("AvgCallDuration")
                        .HasColumnType("float");

                    b.Property<double>("AvgCallWaitingDuration")
                        .HasColumnType("float");

                    b.Property<int>("BranchComplTicketQty")
                        .HasColumnType("int");

                    b.Property<int>("ComplaintTicketQty")
                        .HasColumnType("int");

                    b.Property<int>("CrmcoursesQty")
                        .HasColumnType("int");

                    b.Property<int>("GanjinehIssuesQty")
                        .HasColumnType("int");

                    b.Property<double>("GanjinehIssuesVol")
                        .HasColumnType("float");

                    b.Property<int>("GanjinehTicketQty")
                        .HasColumnType("int");

                    b.Property<int>("GoharTicketQty")
                        .HasColumnType("int");

                    b.Property<int>("GoharandServatIssuesQty")
                        .HasColumnType("int");

                    b.Property<double>("GoharandServatIssuesVol")
                        .HasColumnType("float");

                    b.Property<int>("IbCardTicketQty")
                        .HasColumnType("int");

                    b.Property<int>("IbCrowdTicketQty")
                        .HasColumnType("int");

                    b.Property<int>("InCallQty")
                        .HasColumnType("int");

                    b.Property<int>("InChatQty")
                        .HasColumnType("int");

                    b.Property<int>("InCompCallQty")
                        .HasColumnType("int");

                    b.Property<int>("InSurveyCallQty")
                        .HasColumnType("int");

                    b.Property<int>("InVmQty")
                        .HasColumnType("int");

                    b.Property<int>("Inticket")
                        .HasColumnType("int");

                    b.Property<string>("Month")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MonthNumber")
                        .HasColumnType("int");

                    b.Property<int>("OnlineChatsurveyQty")
                        .HasColumnType("int");

                    b.Property<int>("OutAccNumEditQty")
                        .HasColumnType("int");

                    b.Property<int>("OutComTrtQty")
                        .HasColumnType("int");

                    b.Property<int>("OutSurveyCallQty")
                        .HasColumnType("int");

                    b.Property<int>("OutVmQty")
                        .HasColumnType("int");

                    b.Property<int>("OutsurveyQty")
                        .HasColumnType("int");

                    b.Property<int>("SejamQty")
                        .HasColumnType("int");

                    b.Property<int>("ServatafarinanTicketQty")
                        .HasColumnType("int");

                    b.Property<int>("SurveyTicketQty")
                        .HasColumnType("int");

                    b.Property<int>("TicketOnlineQty")
                        .HasColumnType("int");

                    b.Property<double>("ToalCallDuration")
                        .HasColumnType("float");

                    b.Property<int>("TotalIssuesQty")
                        .HasColumnType("int");

                    b.Property<double>("TotalIssuesVol")
                        .HasColumnType("float");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Crmmrid");

                    b.ToTable("CrmMonthlyReports");
                });

            modelBuilder.Entity("IBshopDemo.Models.FinancialMonthlyReport", b =>
                {
                    b.Property<int>("FinancialMonthlyReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FinancialMonthlyReportId"));

                    b.Property<int>("CheckedfundQty")
                        .HasColumnType("int");

                    b.Property<int>("ColPrpQty")
                        .HasColumnType("int");

                    b.Property<int>("ContQty")
                        .HasColumnType("int");

                    b.Property<int>("LblPrpQty")
                        .HasColumnType("int");

                    b.Property<string>("Month")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MonthNumber")
                        .HasColumnType("int");

                    b.Property<int>("MtnprpQty")
                        .HasColumnType("int");

                    b.Property<int>("PersonnelSetQty")
                        .HasColumnType("int");

                    b.Property<int>("PrpReqQty")
                        .HasColumnType("int");

                    b.Property<int>("Recivedgaurantee")
                        .HasColumnType("int");

                    b.Property<int>("ResFundInstallmenQty")
                        .HasColumnType("int");

                    b.Property<int>("RestaxinstallmentQty")
                        .HasColumnType("int");

                    b.Property<int>("TaminInstallmentDelay")
                        .HasColumnType("int");

                    b.Property<int>("TaminInstallmentQty")
                        .HasColumnType("int");

                    b.Property<int>("TaminPenaltyVol")
                        .HasColumnType("int");

                    b.Property<int>("TaxInstallmentDelay")
                        .HasColumnType("int");

                    b.Property<int>("TranCommissionQty")
                        .HasColumnType("int");

                    b.Property<int>("TreasuryBillsQty")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("FinancialMonthlyReportId");

                    b.ToTable("FinancialMonthlyReports");
                });

            modelBuilder.Entity("IBshopDemo.Models.FinancialSuperMarketMonthlyReport", b =>
                {
                    b.Property<int>("SuperMrid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SuperMrid"));

                    b.Property<int>("ActivationQty")
                        .HasColumnType("int");

                    b.Property<int>("AndookhtehIssueReqQty")
                        .HasColumnType("int");

                    b.Property<int>("AndookhtehIssuesVol")
                        .HasColumnType("int");

                    b.Property<int>("AndookhtehRevokeReqQty")
                        .HasColumnType("int");

                    b.Property<int>("AndookhtehRevokeVol")
                        .HasColumnType("int");

                    b.Property<int>("AuthenticationQty")
                        .HasColumnType("int");

                    b.Property<int>("CardIssuanceQty")
                        .HasColumnType("int");

                    b.Property<int>("CreaditQty")
                        .HasColumnType("int");

                    b.Property<int>("CreaditVol")
                        .HasColumnType("int");

                    b.Property<int>("CustomersReplyQty")
                        .HasColumnType("int");

                    b.Property<int>("EditQty")
                        .HasColumnType("int");

                    b.Property<int>("GanjinehIssueReqQty")
                        .HasColumnType("int");

                    b.Property<int>("GanjinehIssuesVol")
                        .HasColumnType("int");

                    b.Property<int>("GanjinehRevokeReqQty")
                        .HasColumnType("int");

                    b.Property<int>("GanjinehRevokeVol")
                        .HasColumnType("int");

                    b.Property<int>("GoharandServatIssueReqQty")
                        .HasColumnType("int");

                    b.Property<int>("GoharandServatRevokeReqQty")
                        .HasColumnType("int");

                    b.Property<int>("GohrandServatIssuesVol")
                        .HasColumnType("int");

                    b.Property<int>("GohrandServatRevokeVol")
                        .HasColumnType("int");

                    b.Property<int>("IbshoppRegisterQty")
                        .HasColumnType("int");

                    b.Property<int>("InsuranceIssued")
                        .HasColumnType("int");

                    b.Property<int>("InvestorsQty")
                        .HasColumnType("int");

                    b.Property<int>("LegalServQty")
                        .HasColumnType("int");

                    b.Property<string>("Month")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MonthNumber")
                        .HasColumnType("int");

                    b.Property<int>("OnlineCodeQty")
                        .HasColumnType("int");

                    b.Property<int>("ReportForCustomerC")
                        .HasColumnType("int");

                    b.Property<int>("ReportForCustomerF")
                        .HasColumnType("int");

                    b.Property<int>("TotIsuuVol")
                        .HasColumnType("int");

                    b.Property<int>("TotRevVol")
                        .HasColumnType("int");

                    b.Property<int>("TotalIbcardVol")
                        .HasColumnType("int");

                    b.Property<int>("TotalIbcrowdVol")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("SuperMrid");

                    b.ToTable("FinancialSuperMarketMonthlyReports");
                });

            modelBuilder.Entity("IBshopDemo.Models.FixIncomeProperty", b =>
                {
                    b.Property<int>("FixIncomeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FixIncomeId"));

                    b.Property<decimal>("AndookhtehIssue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("AndookhtehRev")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BrancheCode")
                        .HasColumnType("int");

                    b.Property<int>("BrancheCodeNavigationBranchCode")
                        .HasColumnType("int");

                    b.Property<int?>("CustomerQty")
                        .HasColumnType("int");

                    b.Property<decimal>("GanjinehIssue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GanjinehRev")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("InComeCenterId")
                        .HasColumnType("int");

                    b.Property<string>("MonthName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MonthNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalIssue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalRev")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("VirIssueBillQty")
                        .HasColumnType("int");

                    b.Property<decimal>("VirIssueBillVol")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("FixIncomeId");

                    b.HasIndex("BrancheCodeNavigationBranchCode");

                    b.HasIndex("InComeCenterId");

                    b.ToTable("FixIncomeProperties");
                });

            modelBuilder.Entity("IBshopDemo.Models.HrMonthlyReport", b =>
                {
                    b.Property<int>("HrmonthlyreportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HrmonthlyreportId"));

                    b.Property<int>("AsuAsgNewPer")
                        .HasColumnType("int");

                    b.Property<int>("BrkFailQty")
                        .HasColumnType("int");

                    b.Property<int>("CoursQty")
                        .HasColumnType("int");

                    b.Property<int>("FloFailQty")
                        .HasColumnType("int");

                    b.Property<int>("Gcissu")
                        .HasColumnType("int");

                    b.Property<int>("GurReqFun")
                        .HasColumnType("int");

                    b.Property<int>("GurReqLtt")
                        .HasColumnType("int");

                    b.Property<int>("HrmhiredQty")
                        .HasColumnType("int");

                    b.Property<int>("HrpersonnelQty")
                        .HasColumnType("int");

                    b.Property<int>("IntQty")
                        .HasColumnType("int");

                    b.Property<int>("LeftQty")
                        .HasColumnType("int");

                    b.Property<int>("LobFailQty")
                        .HasColumnType("int");

                    b.Property<int>("MngRfailQty")
                        .HasColumnType("int");

                    b.Property<string>("Month")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MonthNumber")
                        .HasColumnType("int");

                    b.Property<int>("Obqty")
                        .HasColumnType("int");

                    b.Property<int>("PerEntCnfQty")
                        .HasColumnType("int");

                    b.Property<int>("PntFailQty")
                        .HasColumnType("int");

                    b.Property<int>("PreFailQty")
                        .HasColumnType("int");

                    b.Property<int>("PyrDedReqLtt")
                        .HasColumnType("int");

                    b.Property<int>("RecLtt")
                        .HasColumnType("int");

                    b.Property<int>("ReplacemntQty")
                        .HasColumnType("int");

                    b.Property<int>("Reqqty")
                        .HasColumnType("int");

                    b.Property<int>("RrfacFail")
                        .HasColumnType("int");

                    b.Property<int>("Rrfail")
                        .HasColumnType("int");

                    b.Property<int>("RsgReq")
                        .HasColumnType("int");

                    b.Property<int>("SendIntLtt")
                        .HasColumnType("int");

                    b.Property<int>("SendOutLtt")
                        .HasColumnType("int");

                    b.Property<int>("SentCvtoDep")
                        .HasColumnType("int");

                    b.Property<int>("SrvAsgNewPer")
                        .HasColumnType("int");

                    b.Property<int>("StrFailQty")
                        .HasColumnType("int");

                    b.Property<int>("TblFailQty")
                        .HasColumnType("int");

                    b.Property<int>("UsedImp")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("HrmonthlyreportId");

                    b.ToTable("HrMonthlyReports");
                });

            modelBuilder.Entity("IBshopDemo.Models.IncomeCenter", b =>
                {
                    b.Property<int>("IncomecenterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IncomecenterId"));

                    b.Property<string>("IncomeCenterName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IncomecenterId");

                    b.ToTable("IncomeCenters");
                });

            modelBuilder.Entity("IBshopDemo.Models.Kpicrm", b =>
                {
                    b.Property<int>("Kpicrmcode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Kpicrmcode"));

                    b.Property<string>("AutAnsPercent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CallAnsSat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CallAnsSpd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CallDuration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Crmiss")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Csat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CusReqMetPer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CusSat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DelAvr")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fcsp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HocallQty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdeCusNeed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LeftCallPercent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MissedCallPercent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MrkOutcall")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NegFb")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewtooldSat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OutcallCostAvg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PerImpPrdSur")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrdAwaPer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SrvPrdSatPer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TicQty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UsersComImpSer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Wtunder3")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Kpicrmcode");

                    b.ToTable("Kpicrms");
                });

            modelBuilder.Entity("IBshopDemo.Models.Kpidevelopment", b =>
                {
                    b.Property<string>("KpidevelomentCode")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AccsugRate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ColRate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IdeCusNeed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InvSugAvgTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewCusinSrvPrd")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewTooldsat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PerImpPrdSur")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrdAwaPer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RdinPrdImp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SolutionAvgTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SugCap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SugInc")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("KpidevelomentCode");

                    b.ToTable("Kpidevelopments");
                });

            modelBuilder.Entity("IBshopDemo.Models.Kpifinancial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AcrFinRepPer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BillIssueAvgTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CnrctrInvoicesMatch")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cnt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CtrTimeDuration")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DemistakeFin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DevPlnBudPer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FixedAssetConflict")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IncBudMeetPer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KpifinCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OdrecintotalRec")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtdecLegRe")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RvwAccConflicts")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RvwInvConflicts")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Kpifinancials");
                });

            modelBuilder.Entity("IBshopDemo.Models.Kpihr", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ColLoyPer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ColSat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EduCap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EduEfc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("GenEduCap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("HrRecDelRat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IctsrvSat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IntColCam")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Kpihrcode")
                        .HasColumnType("int");

                    b.Property<string>("MgmEduCap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MistakeinPersonalInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OutcallCostAvg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PapConCap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProEduCap")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecDelRat")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RecEff")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ReqToNeed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Sal")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SalMistakePerc")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SurveyFeedback")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TrnColeagPer")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Kpihrs");
                });

            modelBuilder.Entity("IBshopDemo.Models.Kpimarket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("BrcMrkRti")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KpimarketingCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LegMrk")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MrkStgDsg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewCusAsset")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewUser")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegistertoIssue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SalePlanDsg")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Kpimarkets");
                });

            modelBuilder.Entity("IBshopDemo.Models.Kpiplanning", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ArchivePer")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DelonPrConf")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EffImpAct")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KmsavePercent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KpiplanCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nps")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OtimpPercentage")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrImPercent")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Kpiplannings");
                });

            modelBuilder.Entity("IBshopDemo.Models.MarketingMonthlyReport", b =>
                {
                    b.Property<int>("Mrkmrid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Mrkmrid"));

                    b.Property<int>("BilboardQty")
                        .HasColumnType("int");

                    b.Property<int?>("BounceRate")
                        .HasColumnType("int");

                    b.Property<int>("ConversationRate")
                        .HasColumnType("int");

                    b.Property<int>("DesignQty")
                        .HasColumnType("int");

                    b.Property<int>("EngQty")
                        .HasColumnType("int");

                    b.Property<int>("GoogleEntTerRate")
                        .HasColumnType("int");

                    b.Property<int>("HoldComptQty")
                        .HasColumnType("int");

                    b.Property<int>("HoldQty")
                        .HasColumnType("int");

                    b.Property<int>("IbcrowdCalllegalCusQty")
                        .HasColumnType("int");

                    b.Property<int>("InsFlwQty")
                        .HasColumnType("int");

                    b.Property<int>("InstFlwQty")
                        .HasColumnType("int");

                    b.Property<int>("KeywordsRank")
                        .HasColumnType("int");

                    b.Property<int>("LinkEntTerRate")
                        .HasColumnType("int");

                    b.Property<int>("LinkdinContentQty")
                        .HasColumnType("int");

                    b.Property<string>("Month")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MonthNumber")
                        .HasColumnType("int");

                    b.Property<int>("NewsQty")
                        .HasColumnType("int");

                    b.Property<int>("NotifPushQty")
                        .HasColumnType("int");

                    b.Property<int>("PostMediaQty")
                        .HasColumnType("int");

                    b.Property<int>("PrdSrvAdvCallQty")
                        .HasColumnType("int");

                    b.Property<int>("RecVidPostQty")
                        .HasColumnType("int");

                    b.Property<int>("RefEntQty")
                        .HasColumnType("int");

                    b.Property<int>("ReportAdvQty")
                        .HasColumnType("int");

                    b.Property<int>("SentSmsQty")
                        .HasColumnType("int");

                    b.Property<int>("SiteEntMonthlyAvg")
                        .HasColumnType("int");

                    b.Property<int>("SmedEntQty")
                        .HasColumnType("int");

                    b.Property<int>("SrchEntQty")
                        .HasColumnType("int");

                    b.Property<int>("StateMedAdvQty")
                        .HasColumnType("int");

                    b.Property<int>("SucCallQty")
                        .HasColumnType("int");

                    b.Property<int>("TlgPostContentQty")
                        .HasColumnType("int");

                    b.Property<int>("ToalInvestVol")
                        .HasColumnType("int");

                    b.Property<int>("TrainPostQty")
                        .HasColumnType("int");

                    b.Property<int>("TrainingCntrctQty")
                        .HasColumnType("int");

                    b.Property<int>("VideoQty")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Mrkmrid");

                    b.ToTable("MarketingMonthlyReports");
                });

            modelBuilder.Entity("IBshopDemo.Models.MixProperty", b =>
                {
                    b.Property<int>("MixIncomeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MixIncomeId"));

                    b.Property<int>("BrancheCode")
                        .HasColumnType("int");

                    b.Property<int>("BrancheCodeNavigationBranchCode")
                        .HasColumnType("int");

                    b.Property<decimal>("GoharIssue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GoharRev")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("IncomeCenterId")
                        .HasColumnType("int");

                    b.Property<string>("MonthName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MonthNumber")
                        .HasColumnType("int");

                    b.Property<decimal>("ServatIssue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ServatRev")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalIssue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalRev")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("MixIncomeId");

                    b.HasIndex("BrancheCodeNavigationBranchCode");

                    b.HasIndex("IncomeCenterId");

                    b.ToTable("MixProperties");
                });

            modelBuilder.Entity("IBshopDemo.Models.OperationKpi", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Answeringspeed")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AppDev")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CusAutAsset")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ErrApp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IbCardAutAvgTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OperationKpicode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PayToCusAvgTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Piapp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SejAutAvgTime")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SucOprRate")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OperationKpis");
                });

            modelBuilder.Entity("IBshopDemo.Models.OperationMonthlyReport", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("AbCandookhtehBranch")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AbCandookhtehBranchRe")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AbCandookhtehOtherBanks")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AbCandookhtehOtherBanksRe")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AbCandookhtehSamaneh")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AbCandookhtehSamanehRe")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AbCandookhtehSandogh")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AbCandookhtehSandoghRe")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AbCandookhtehShahr")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AbCandookhtehShahrRe")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AbCandookhtehShahrnet")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AbCandookhtehShahrnetRe")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AbCandookhtehTamaddon")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AbCandookhtehTamaddonRe")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AbCandookhtehTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AbCandookhtehTotalRe")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AbCganjinehBranches")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AbCganjinehBranchesRe")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AbCganjinehSamaneh")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AbCganjinehSamanehRe")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AbCganjinehSandogh")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AbCganjinehSandoghRe")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AbCganjinehShahr")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AbCganjinehShahrRe")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AbCganjinehShahrnet")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AbCganjinehShahrnetRe")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AbCganjinehTamaddon")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AbCganjinehTamaddonRe")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AbCganjinehTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AbCganjinehTotalRe")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AbCgoharBranch")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AbCgoharBranchRe")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AbCgoharSamaneh")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AbCgoharSamanehRe")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AbCgoharSandogh")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AbCgoharSandoghRe")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AbCgoharTamaddon")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AbCgoharTamaddonRe")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AbCgoharTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AbCgoharTotalRe")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AbCservatBranch")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AbCservatBranchRe")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AbCservatSamaneh")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AbCservatSamanehRe")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AbCservatSandogh")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AbCservatSandoghRe")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AbCservatTamaddon")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AbCservatTamaddonRe")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AbCservatTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AbCservatTotalRe")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BillConflictReqQty")
                        .HasColumnType("int");

                    b.Property<int>("BkgCrdQty")
                        .HasColumnType("int");

                    b.Property<int>("BkgCrdVol")
                        .HasColumnType("int");

                    b.Property<int>("BkgNewCustomer")
                        .HasColumnType("int");

                    b.Property<int>("BkgReqCnfqty")
                        .HasColumnType("int");

                    b.Property<int>("BranchInternetConflictReqQty")
                        .HasColumnType("int");

                    b.Property<int>("FixedConflictQty")
                        .HasColumnType("int");

                    b.Property<int>("IntternetEntranceConflictReq")
                        .HasColumnType("int");

                    b.Property<string>("Month")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MonthNumber")
                        .HasColumnType("int");

                    b.Property<int>("Oprmrid")
                        .HasColumnType("int");

                    b.Property<int>("PoseConflictReqQty")
                        .HasColumnType("int");

                    b.Property<int>("RemotChcAut")
                        .HasColumnType("int");

                    b.Property<int>("SmsinternetConflictReqQty")
                        .HasColumnType("int");

                    b.Property<int>("TotalChcSejam")
                        .HasColumnType("int");

                    b.Property<int>("TotalConflictsProcess")
                        .HasColumnType("int");

                    b.Property<int>("TotalEditAcc")
                        .HasColumnType("int");

                    b.Property<int>("TotalIbcardIssuesQty")
                        .HasColumnType("int");

                    b.Property<int>("TotalIbcardIssuesVol")
                        .HasColumnType("int");

                    b.Property<int>("TotalIdeEdit")
                        .HasColumnType("int");

                    b.Property<int>("TotalIssuCrt")
                        .HasColumnType("int");

                    b.Property<int>("TotalLegAut")
                        .HasColumnType("int");

                    b.Property<int>("TotalTransferVol")
                        .HasColumnType("int");

                    b.Property<int>("TotalmsgQty")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("OperationMonthlyReports");
                });

            modelBuilder.Entity("IBshopDemo.Models.ProcessDesignMonthlyReport", b =>
                {
                    b.Property<int>("ProcessDesignMrid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProcessDesignMrid"));

                    b.Property<int>("AsmPrc")
                        .HasColumnType("int");

                    b.Property<int>("CrmcommHold")
                        .HasColumnType("int");

                    b.Property<int>("CrmdoneCmm")
                        .HasColumnType("int");

                    b.Property<int>("CrmfailCmm")
                        .HasColumnType("int");

                    b.Property<int>("DevCommHold")
                        .HasColumnType("int");

                    b.Property<int>("DevDoneCmm")
                        .HasColumnType("int");

                    b.Property<int>("DevFailCmm")
                        .HasColumnType("int");

                    b.Property<int>("DlgQty")
                        .HasColumnType("int");

                    b.Property<int>("FormQty")
                        .HasColumnType("int");

                    b.Property<int>("IndexQty")
                        .HasColumnType("int");

                    b.Property<int>("InsQty")
                        .HasColumnType("int");

                    b.Property<int>("KpimonitoringQty")
                        .HasColumnType("int");

                    b.Property<string>("Month")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MonthNumber")
                        .HasColumnType("int");

                    b.Property<int>("MrkDoneCmm")
                        .HasColumnType("int");

                    b.Property<int>("MrkFailCmm")
                        .HasColumnType("int");

                    b.Property<int>("MrkcommHold")
                        .HasColumnType("int");

                    b.Property<int>("PrcDesign")
                        .HasColumnType("int");

                    b.Property<int>("PrcdQty")
                        .HasColumnType("int");

                    b.Property<int>("RegQty")
                        .HasColumnType("int");

                    b.Property<int>("RelInsQty")
                        .HasColumnType("int");

                    b.Property<int>("RelPrcdQty")
                        .HasColumnType("int");

                    b.Property<int>("RelReqQty")
                        .HasColumnType("int");

                    b.Property<int>("ReviewPrc")
                        .HasColumnType("int");

                    b.Property<int>("ReviwIndxQty")
                        .HasColumnType("int");

                    b.Property<int?>("Year")
                        .HasColumnType("int");

                    b.HasKey("ProcessDesignMrid");

                    b.ToTable("ProcessDesignMonthlyReports");
                });

            modelBuilder.Entity("IBshopDemo.Models.Product", b =>
                {
                    b.Property<int>("ProductsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductsId"));

                    b.Property<int>("BrancheCode")
                        .HasColumnType("int");

                    b.Property<int>("BrancheCodeNavigationBranchCode")
                        .HasColumnType("int");

                    b.Property<int>("CardQty")
                        .HasColumnType("int");

                    b.Property<decimal>("DealValue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("IbcardIssueQty")
                        .HasColumnType("int");

                    b.Property<decimal>("IbcrowdVol")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Income")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("IncomeCenterId")
                        .HasColumnType("int");

                    b.Property<int>("KargozariBoursCode")
                        .HasColumnType("int");

                    b.Property<string>("MonthName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MonthNumber")
                        .HasColumnType("int");

                    b.HasKey("ProductsId");

                    b.HasIndex("BrancheCodeNavigationBranchCode");

                    b.HasIndex("IncomeCenterId");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("IBshopDemo.Models.ProductDevelopmentMontylyReport", b =>
                {
                    b.Property<int>("DevMrid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DevMrid"));

                    b.Property<int>("AcceptedSuggestQty")
                        .HasColumnType("int");

                    b.Property<int>("CheckedSuggestQty")
                        .HasColumnType("int");

                    b.Property<int>("EconomicalSuggestQty")
                        .HasColumnType("int");

                    b.Property<int>("IbcComplQty")
                        .HasColumnType("int");

                    b.Property<int>("IbcCreadiCardReqQty")
                        .HasColumnType("int");

                    b.Property<int>("IbcCreaditCardCustQty")
                        .HasColumnType("int");

                    b.Property<int>("IbcCreaditCardProcessAvgTime")
                        .HasColumnType("int");

                    b.Property<int>("IbwDesignQty")
                        .HasColumnType("int");

                    b.Property<int>("IbwDesignTime")
                        .HasColumnType("int");

                    b.Property<int>("IbwDesignVol")
                        .HasColumnType("int");

                    b.Property<string>("Month")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MonthNumber")
                        .HasColumnType("int");

                    b.Property<int>("SuggestPersonnelQty")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("DevMrid");

                    b.ToTable("ProductDevelopmentMontylyReports");
                });

            modelBuilder.Entity("IBshopDemo.Models.QaMonthlyReport", b =>
                {
                    b.Property<int>("Qamrid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Qamrid"));

                    b.Property<int>("AgradeQty")
                        .HasColumnType("int");

                    b.Property<int>("ApgradeQty")
                        .HasColumnType("int");

                    b.Property<int>("BgradeQty")
                        .HasColumnType("int");

                    b.Property<int>("CalMgtIncQty")
                        .HasColumnType("int");

                    b.Property<int>("CalMgtOutQty")
                        .HasColumnType("int");

                    b.Property<int>("CalMgtPerIncQty")
                        .HasColumnType("int");

                    b.Property<int>("CalMgtPerOutQty")
                        .HasColumnType("int");

                    b.Property<int>("CgradeQty")
                        .HasColumnType("int");

                    b.Property<int>("DgradeQty")
                        .HasColumnType("int");

                    b.Property<int>("EgradeQty")
                        .HasColumnType("int");

                    b.Property<int>("FgradeQty")
                        .HasColumnType("int");

                    b.Property<int>("GgradeQty")
                        .HasColumnType("int");

                    b.Property<int>("HgradeQty")
                        .HasColumnType("int");

                    b.Property<int>("KnwFailIncQty")
                        .HasColumnType("int");

                    b.Property<int>("KnwFailPerIncQty")
                        .HasColumnType("int");

                    b.Property<string>("Month")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("MonthNumber")
                        .HasColumnType("int");

                    b.Property<int>("ProFailChatQty")
                        .HasColumnType("int");

                    b.Property<int>("ProFailIncQty")
                        .HasColumnType("int");

                    b.Property<int>("ProFailOutQty")
                        .HasColumnType("int");

                    b.Property<int>("ProFailPerChatQty")
                        .HasColumnType("int");

                    b.Property<int>("ProFailPerIncQty")
                        .HasColumnType("int");

                    b.Property<int>("ProFailPerOutQty")
                        .HasColumnType("int");

                    b.Property<int?>("RepFail")
                        .HasColumnType("int");

                    b.Property<int>("SurFailChatQty")
                        .HasColumnType("int");

                    b.Property<int>("SurFailIncQty")
                        .HasColumnType("int");

                    b.Property<int>("SurFailOutQty")
                        .HasColumnType("int");

                    b.Property<int>("SurFailPerChatQty")
                        .HasColumnType("int");

                    b.Property<int>("SurFailPerIncQty")
                        .HasColumnType("int");

                    b.Property<int>("SurFailPerOutQty")
                        .HasColumnType("int");

                    b.Property<int?>("SurveyChatOnline")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int>("SysFailIncQty")
                        .HasColumnType("int");

                    b.Property<int>("SysFailPerIncQty")
                        .HasColumnType("int");

                    b.Property<int>("TicFailChatQty")
                        .HasColumnType("int");

                    b.Property<int>("TicFailIncQty")
                        .HasColumnType("int");

                    b.Property<int>("TicFailOutQty")
                        .HasColumnType("int");

                    b.Property<int>("TicFailPerChatQty")
                        .HasColumnType("int");

                    b.Property<int>("TicFailPerIncQty")
                        .HasColumnType("int");

                    b.Property<int>("TicFailPerOutQty")
                        .HasColumnType("int");

                    b.Property<int>("TimFailChatQty")
                        .HasColumnType("int");

                    b.Property<int>("TimFailPerChatQty")
                        .HasColumnType("int");

                    b.Property<int>("ToalOnlineChat")
                        .HasColumnType("int");

                    b.Property<int>("TotalChcIncCallQty")
                        .HasColumnType("int");

                    b.Property<int>("TotalChcOutCallQty")
                        .HasColumnType("int");

                    b.Property<int>("TotalCheckedOnlineChat")
                        .HasColumnType("int");

                    b.Property<int>("TotalPersonnelIncCallQty")
                        .HasColumnType("int");

                    b.Property<int>("TotalPersonnelOutCallQty")
                        .HasColumnType("int");

                    b.Property<int>("WelFailIncQty")
                        .HasColumnType("int");

                    b.Property<int>("WelFailPerIncQty")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Qamrid");

                    b.ToTable("QaMonthlyReports");
                });

            modelBuilder.Entity("IBshopDemo.Models.Report", b =>
                {
                    b.Property<int>("ReportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReportId"));

                    b.Property<string>("ReportName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReportId");

                    b.ToTable("Reports");
                });

            modelBuilder.Entity("IBshopDemo.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("RoleUniqeCode")
                        .HasColumnType("int");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("IBshopDemo.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NationalCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("IBshopDemo.Models.UserRole", b =>
                {
                    b.Property<long>("UserRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("UserRoleId"));

                    b.Property<int?>("RoleId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("UserRoleId");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("IBshopDemo.Models.FixIncomeProperty", b =>
                {
                    b.HasOne("IBshopDemo.Models.BranchesInfo", "BrancheCodeNavigation")
                        .WithMany("FixIncomeProperties")
                        .HasForeignKey("BrancheCodeNavigationBranchCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IBshopDemo.Models.IncomeCenter", "InComeCenter")
                        .WithMany("FixIncomeProperties")
                        .HasForeignKey("InComeCenterId");

                    b.Navigation("BrancheCodeNavigation");

                    b.Navigation("InComeCenter");
                });

            modelBuilder.Entity("IBshopDemo.Models.MixProperty", b =>
                {
                    b.HasOne("IBshopDemo.Models.BranchesInfo", "BrancheCodeNavigation")
                        .WithMany("MixProperties")
                        .HasForeignKey("BrancheCodeNavigationBranchCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IBshopDemo.Models.IncomeCenter", "IncomeCenter")
                        .WithMany("MixProperties")
                        .HasForeignKey("IncomeCenterId");

                    b.Navigation("BrancheCodeNavigation");

                    b.Navigation("IncomeCenter");
                });

            modelBuilder.Entity("IBshopDemo.Models.Product", b =>
                {
                    b.HasOne("IBshopDemo.Models.BranchesInfo", "BrancheCodeNavigation")
                        .WithMany("Products")
                        .HasForeignKey("BrancheCodeNavigationBranchCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IBshopDemo.Models.IncomeCenter", "IncomeCenter")
                        .WithMany("Products")
                        .HasForeignKey("IncomeCenterId");

                    b.Navigation("BrancheCodeNavigation");

                    b.Navigation("IncomeCenter");
                });

            modelBuilder.Entity("IBshopDemo.Models.UserRole", b =>
                {
                    b.HasOne("IBshopDemo.Models.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId");

                    b.HasOne("IBshopDemo.Models.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId");

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("IBshopDemo.Models.BranchesInfo", b =>
                {
                    b.Navigation("FixIncomeProperties");

                    b.Navigation("MixProperties");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("IBshopDemo.Models.IncomeCenter", b =>
                {
                    b.Navigation("FixIncomeProperties");

                    b.Navigation("MixProperties");

                    b.Navigation("Products");
                });

            modelBuilder.Entity("IBshopDemo.Models.Role", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("IBshopDemo.Models.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
